[phases.setup]
nixPkgs = ["php81", "php81Extensions.pdo_mysql", "php81Extensions.mbstring", "php81Extensions.exif", "php81Extensions.bcmath", "php81Extensions.gd", "php81Extensions.intl", "php81Extensions.zip"]

[phases.build]
cmds = [
  "composer install --no-interaction --optimize-autoloader",
  "cp .env.example .env",
  "php artisan key:generate --force"
]

[start]
cmd = "cp .env.railway .env && php -S 0.0.0.0:${PORT:-8000} -t public" 