[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 600
healthcheckInterval = 15
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 