"https://{default}/":
    type: upstream
    upstream: "app:http"
    cache:
        enabled: true
        cookies: ['/^SS?ESS/', 'PHPSESSID']

"https://www.{default}/":
    type: redirect
    to: "https://{default}/" 